# Digital Ocean App Platform Configuration
# This file is optional - App Platform can auto-detect Next.js
# Use this for advanced configuration

name: eazzypay
region: nyc1  # Change to closest region: nyc1, sfo3, ams3, sgp1, etc.

# Web Service Component
services:
  - name: web
    source_dir: /
    github:
      repo: YOUR_GITHUB_USERNAME/paymentvalut  # Update with your repo
      branch: main
      deploy_on_push: true
    
    # Build Configuration
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    
    # Instance Configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # Options: basic-xxs, basic-xs, basic-s, basic-m, etc.
    # basic-xxs: 512MB RAM / 0.25 vCPU ($5/month)
    # basic-xs: 1GB RAM / 0.5 vCPU ($12/month) - Recommended minimum
    # basic-s: 2GB RAM / 1 vCPU ($24/month) - For production
    
    # Routes
    routes:
      - path: /
    
    # Health Check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment Variables
    # Note: Add sensitive variables in App Platform Dashboard instead
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"  # App Platform uses 8080 by default
      # Add other non-sensitive defaults here
      # Sensitive vars (JWT_SECRET, API keys, etc.) should be added in dashboard

# Optional: Worker Component for Cron Jobs
# Uncomment and configure if you want scheduled jobs
# workers:
#   - name: disburse-retry-worker
#     source_dir: /
#     github:
#       repo: YOUR_GITHUB_USERNAME/paymentvalut
#       branch: main
#     run_command: node scripts/cron-disburse-retry.js
#     instance_count: 1
#     instance_size_slug: basic-xxs
#     # Schedule using App Platform's cron feature or GitHub Actions

