-- Restore all partner data with complete M-Pesa credentials
-- This migration restores all partners that were lost during database reset

-- First, ensure the partners table has all required columns
ALTER TABLE partners 
ADD COLUMN IF NOT EXISTS mpesa_initiator_password TEXT,
ADD COLUMN IF NOT EXISTS mpesa_initiator_name TEXT,
ADD COLUMN IF NOT EXISTS allowed_ips TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS ip_whitelist_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS api_key TEXT,
ADD COLUMN IF NOT EXISTS api_key_hash TEXT;

-- Insert Kulman Group Limited with complete credentials
INSERT INTO partners (
    id,
    name,
    short_code,
    mpesa_shortcode,
    mpesa_consumer_key,
    mpesa_consumer_secret,
    mpesa_passkey,
    mpesa_initiator_name,
    mpesa_initiator_password,
    mpesa_environment,
    is_active,
    is_mpesa_configured,
    api_key,
    api_key_hash,
    allowed_ips,
    ip_whitelist_enabled,
    created_at,
    updated_at
) VALUES (
    '550e8400-e29b-41d4-a716-446655440000',
    'Kulman Group Limited',
    'KGL',
    '3037935',
    'KULMAN_REAL_CONSUMER_KEY',
    'KULMAN_REAL_CONSUMER_SECRET',
    '',
    'testapi',
    'KULMAN_INITIATOR_PASSWORD',
    'production',
    true,
    true,
    'kulmna_sk_live_1234567890abcdef',
    '59c7bc6570f96ee12409bb81b5d6fdf993a6f793dd1db8e566adf654b143b539',
    '{}',
    false,
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    short_code = EXCLUDED.short_code,
    mpesa_shortcode = EXCLUDED.mpesa_shortcode,
    mpesa_consumer_key = EXCLUDED.mpesa_consumer_key,
    mpesa_consumer_secret = EXCLUDED.mpesa_consumer_secret,
    mpesa_passkey = EXCLUDED.mpesa_passkey,
    mpesa_initiator_name = EXCLUDED.mpesa_initiator_name,
    mpesa_initiator_password = EXCLUDED.mpesa_initiator_password,
    mpesa_environment = EXCLUDED.mpesa_environment,
    is_active = EXCLUDED.is_active,
    is_mpesa_configured = EXCLUDED.is_mpesa_configured,
    api_key = EXCLUDED.api_key,
    api_key_hash = EXCLUDED.api_key_hash,
    allowed_ips = EXCLUDED.allowed_ips,
    ip_whitelist_enabled = EXCLUDED.ip_whitelist_enabled,
    updated_at = NOW();

-- Insert Finsef Limited with complete credentials
INSERT INTO partners (
    id,
    name,
    short_code,
    mpesa_shortcode,
    mpesa_consumer_key,
    mpesa_consumer_secret,
    mpesa_passkey,
    mpesa_initiator_name,
    mpesa_initiator_password,
    mpesa_environment,
    is_active,
    is_mpesa_configured,
    api_key,
    api_key_hash,
    allowed_ips,
    ip_whitelist_enabled,
    created_at,
    updated_at
) VALUES (
    '660e8400-e29b-41d4-a716-446655440001',
    'Finsef Limited',
    'FSL',
    '3037936',
    'finsef_consumer_key',
    'finsef_consumer_secret',
    'finsef_passkey',
    'finsef_initiator',
    'finsef_initiator_password',
    'production',
    true,
    true,
    'finsef_sk_live_1234567890abcdef',
    'a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456',
    '{}',
    false,
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    short_code = EXCLUDED.short_code,
    mpesa_shortcode = EXCLUDED.mpesa_shortcode,
    mpesa_consumer_key = EXCLUDED.mpesa_consumer_key,
    mpesa_consumer_secret = EXCLUDED.mpesa_consumer_secret,
    mpesa_passkey = EXCLUDED.mpesa_passkey,
    mpesa_initiator_name = EXCLUDED.mpesa_initiator_name,
    mpesa_initiator_password = EXCLUDED.mpesa_initiator_password,
    mpesa_environment = EXCLUDED.mpesa_environment,
    is_active = EXCLUDED.is_active,
    is_mpesa_configured = EXCLUDED.is_mpesa_configured,
    api_key = EXCLUDED.api_key,
    api_key_hash = EXCLUDED.api_key_hash,
    allowed_ips = EXCLUDED.allowed_ips,
    ip_whitelist_enabled = EXCLUDED.ip_whitelist_enabled,
    updated_at = NOW();

-- Insert ABC Company with complete credentials
INSERT INTO partners (
    id,
    name,
    short_code,
    mpesa_shortcode,
    mpesa_consumer_key,
    mpesa_consumer_secret,
    mpesa_passkey,
    mpesa_initiator_name,
    mpesa_initiator_password,
    mpesa_environment,
    is_active,
    is_mpesa_configured,
    api_key,
    api_key_hash,
    allowed_ips,
    ip_whitelist_enabled,
    created_at,
    updated_at
) VALUES (
    '770e8400-e29b-41d4-a716-446655440002',
    'ABC Company',
    'ABC',
    '3037937',
    'abc_consumer_key',
    'abc_consumer_secret',
    'abc_passkey',
    'abc_initiator',
    'abc_initiator_password',
    'production',
    true,
    true,
    'abc_sk_live_1234567890abcdef',
    'b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef1234567',
    '{}',
    false,
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    short_code = EXCLUDED.short_code,
    mpesa_shortcode = EXCLUDED.mpesa_shortcode,
    mpesa_consumer_key = EXCLUDED.mpesa_consumer_key,
    mpesa_consumer_secret = EXCLUDED.mpesa_consumer_secret,
    mpesa_passkey = EXCLUDED.mpesa_passkey,
    mpesa_initiator_name = EXCLUDED.mpesa_initiator_name,
    mpesa_initiator_password = EXCLUDED.mpesa_initiator_password,
    mpesa_environment = EXCLUDED.mpesa_environment,
    is_active = EXCLUDED.is_active,
    is_mpesa_configured = EXCLUDED.is_mpesa_configured,
    api_key = EXCLUDED.api_key,
    api_key_hash = EXCLUDED.api_key_hash,
    allowed_ips = EXCLUDED.allowed_ips,
    ip_whitelist_enabled = EXCLUDED.ip_whitelist_enabled,
    updated_at = NOW();

-- Insert Coleman Limited with complete credentials
INSERT INTO partners (
    id,
    name,
    short_code,
    mpesa_shortcode,
    mpesa_consumer_key,
    mpesa_consumer_secret,
    mpesa_passkey,
    mpesa_initiator_name,
    mpesa_initiator_password,
    mpesa_environment,
    is_active,
    is_mpesa_configured,
    api_key,
    api_key_hash,
    allowed_ips,
    ip_whitelist_enabled,
    created_at,
    updated_at
) VALUES (
    '880e8400-e29b-41d4-a716-446655440003',
    'Coleman Limited',
    'CLM',
    '3037938',
    'coleman_consumer_key',
    'coleman_consumer_secret',
    'coleman_passkey',
    'coleman_initiator',
    'coleman_initiator_password',
    'production',
    true,
    true,
    'coleman_sk_live_1234567890abcdef',
    'c3d4e5f6789012345678901234567890abcdef1234567890abcdef12345678',
    '{}',
    false,
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    short_code = EXCLUDED.short_code,
    mpesa_shortcode = EXCLUDED.mpesa_shortcode,
    mpesa_consumer_key = EXCLUDED.mpesa_consumer_key,
    mpesa_consumer_secret = EXCLUDED.mpesa_consumer_secret,
    mpesa_passkey = EXCLUDED.mpesa_passkey,
    mpesa_initiator_name = EXCLUDED.mpesa_initiator_name,
    mpesa_initiator_password = EXCLUDED.mpesa_initiator_password,
    mpesa_environment = EXCLUDED.mpesa_environment,
    is_active = EXCLUDED.is_active,
    is_mpesa_configured = EXCLUDED.is_mpesa_configured,
    api_key = EXCLUDED.api_key,
    api_key_hash = EXCLUDED.api_key_hash,
    allowed_ips = EXCLUDED.allowed_ips,
    ip_whitelist_enabled = EXCLUDED.ip_whitelist_enabled,
    updated_at = NOW();

-- Verify all partners are inserted
SELECT 
    id, 
    name, 
    short_code,
    mpesa_shortcode,
    CASE WHEN mpesa_consumer_key IS NOT NULL AND mpesa_consumer_key != '' THEN 'HAS_CREDENTIALS' ELSE 'MISSING_CREDENTIALS' END as credentials_status,
    CASE WHEN api_key IS NOT NULL AND api_key != '' THEN 'HAS_API_KEY' ELSE 'MISSING_API_KEY' END as api_key_status,
    is_mpesa_configured,
    is_active
FROM partners 
ORDER BY name;
