name: Balance Monitor

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Balance Check
        run: |
          curl -X POST ${{ secrets.API_URL }}/api/balance/trigger-check \
            -H "Content-Type: application/json" \
            -d '{"all_tenants": true}'
        env:
          API_URL: ${{ secrets.API_URL }}
